name: Deployment

on:
  push:
    branches: [main]

jobs:
  ci:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: |
          npm install
          npm run test-component

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
